"""add parent-child chunk fields and hnsw index

Revision ID: 540f348503de
Revises: 9352792701d3
Create Date: 2026-08-07 03:46:04.713503

"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '540f348503de'
down_revision: str | Sequence[str] | None = '9352792701d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('parent_chunk_id', sa.Uuid(), nullable=True))
    op.add_column('chunks', sa.Column('embedding_model', sa.String(), nullable=False))
    op.add_column('chunks', sa.Column('embedding_version', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('heading_path', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('ingestion_strategy', sa.String(), nullable=False))
    op.add_column('chunks', sa.Column('token_count', sa.Integer(), nullable=True))
    op.alter_column('chunks', 'embedding',
               existing_type=Vector(1024),
               nullable=True)
    op.alter_column('chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_parent_chunk_id'), 'chunks', ['parent_chunk_id'], unique=False)
    op.create_foreign_key('fk_chunks_parent_chunk_id', 'chunks', 'chunks', ['parent_chunk_id'], ['id'])
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw ON chunks "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 128)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding_hnsw")
    op.drop_constraint('fk_chunks_parent_chunk_id', 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_parent_chunk_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.alter_column('chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chunks', 'embedding',
               existing_type=Vector(1024),
               nullable=False)
    op.drop_column('chunks', 'token_count')
    op.drop_column('chunks', 'ingestion_strategy')
    op.drop_column('chunks', 'heading_path')
    op.drop_column('chunks', 'embedding_version')
    op.drop_column('chunks', 'embedding_model')
    op.drop_column('chunks', 'parent_chunk_id')
    # ### end Alembic commands ###
