"""add correlation_id to documents

Revision ID: 6358bb32b8c2
Revises: 768852d2cda2
Create Date: 2026-08-19 20:06:24.085543

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6358bb32b8c2"
down_revision: str | Sequence[str] | None = "768852d2cda2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("correlation_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "correlation_id")
    # ### end Alembic commands ###
