"""add content_hash to documents

Revision ID: fb0ea0694750
Revises: 9af3ac453599
Create Date: 2026-09-17 21:32:55.827536

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb0ea0694750"
down_revision: str | Sequence[str] | None = "9af3ac453599"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("content_hash", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "content_hash")
    # ### end Alembic commands ###
